version: '2'
services:
  php:
    build: ./
    volumes:
      - .:/srv/app
    ports:
      - '8000:80'
    environment:
     - VIRTUAL_HOST=chat.test.com
    depends_on:
              - db        
  db:
    build: ./docker/mysql
